<?php
require __DIR__ . '/includes/bootstrap.php';
$page = trim((string)($_GET['page'] ?? 'home'), '/');
$allowed = ['home','shop','product','cart','checkout','login','register','account','logout','about','contact','faqs','terms','privacy','returns','track'];
if (!in_array($page, $allowed, true)) { http_response_code(404); $page='404'; }
$authError='';
if($page==='logout'){unset($_SESSION['user_id']);session_regenerate_id(true);header('Location: '.url('?page=login'));exit;}
if($_SERVER['REQUEST_METHOD']==='POST'&&in_array($page,['login','register'],true)){
 verify_csrf();
 if(!$pdo){$authError='Database connection is unavailable.';}
 elseif($page==='register'){
  $name=trim($_POST['name']??'');$email=strtolower(trim($_POST['email']??''));$phone=trim($_POST['phone']??'');$password=$_POST['password']??'';
  if($name===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<8){$authError='Enter a valid name, email and password of at least 8 characters.';}
  else try{$q=$pdo->prepare("INSERT INTO users(name,email,phone,password) VALUES(?,?,?,?)");$q->execute([$name,$email,$phone,password_hash($password,PASSWORD_DEFAULT)]);$_SESSION['user_id']=(int)$pdo->lastInsertId();session_regenerate_id(true);header('Location: '.url('?page=account'));exit;}catch(Throwable $exception){$authError='That email or phone is already registered.';}
 } else {
  $login=trim($_POST['login']??'');$q=$pdo->prepare("SELECT id,password,is_blocked FROM users WHERE email=? OR phone=? LIMIT 1");$q->execute([$login,$login]);$user=$q->fetch();
  if($user&&!$user['is_blocked']&&password_verify($_POST['password']??'',$user['password'])){$_SESSION['user_id']=(int)$user['id'];session_regenerate_id(true);header('Location: '.url('?page=account'));exit;}
  $authError='Email/phone or password is incorrect.';
 }
}
if($page==='account'&&!customer()){header('Location: '.url('?page=login&next=account'));exit;}
$query=trim((string)($_GET['q']??''));$selectedCategory=trim((string)($_GET['category']??''));
$items = products($query,$selectedCategory);
$allCategories = active_categories();
$selectedCategoryRow = $selectedCategory ? category_by_name($selectedCategory) : null;
$productDetail = $page === 'product' ? product_by_id((int)($_GET['id'] ?? 0)) : null;
$seo = seo_meta($page, ['category' => $selectedCategory, 'category_row' => $selectedCategoryRow, 'product' => $productDetail, 'product_name' => $productDetail['name'] ?? null]);
$title = $seo['title'];
$cartCount = array_sum(array_column($_SESSION['cart'] ?? [], 'qty'));
$homeBanners=active_banners();
$homeCategories=$allCategories;
$siteLogo=setting('logo','uploads/logo/darbar-sweets-logo.png');
$siteName=setting('site_name','Darbar Sweets');
?>
<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="<?=e($seo['description'])?>">
<meta name="keywords" content="<?=e($seo['keywords'])?>">
<meta name="robots" content="index,follow">
<link rel="canonical" href="<?=e($seo['canonical'])?>">
<meta property="og:type" content="<?= $page === 'product' ? 'product' : 'website' ?>">
<meta property="og:site_name" content="<?=e($siteName)?>">
<meta property="og:title" content="<?=e($title)?> · <?=e($siteName)?>">
<meta property="og:description" content="<?=e($seo['description'])?>">
<meta property="og:url" content="<?=e($seo['canonical'])?>">
<meta property="og:image" content="<?=e(url($seo['image']))?>">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="<?=e($title)?> · <?=e($siteName)?>">
<meta name="twitter:description" content="<?=e($seo['description'])?>">
<meta name="twitter:image" content="<?=e(url($seo['image']))?>">
<title><?=e($title)?> · <?=e($siteName)?></title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@600;700&display=swap" rel="stylesheet">
<style>:root{--color-primary:<?=e(setting('color_primary','#006d63'))?>;--color-secondary:<?=e(setting('color_secondary','#ef8c00'))?>}</style>
<link rel="stylesheet" href="<?=url('assets/css/style.css')?>">
<?php if ($page === 'home'): ?><script type="application/ld+json"><?=json_encode(['@context'=>'https://schema.org','@type'=>'Store','name'=>$siteName,'description'=>$seo['description'],'url'=>$seo['canonical'],'image'=>url($seo['image']),'address'=>['@type'=>'PostalAddress','addressLocality'=>'Karachi','addressCountry'=>'PK']], JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?></script><?php elseif ($page === 'product' && $productDetail): ?><script type="application/ld+json"><?=json_encode(['@context'=>'https://schema.org','@type'=>'Product','name'=>$productDetail['name'],'description'=>$productDetail['short_description'],'image'=>url($productDetail['image']),'sku'=>$productDetail['sku'],'offers'=>['@type'=>'Offer','priceCurrency'=>'PKR','price'=>$productDetail['price'],'availability'=>'https://schema.org/InStock']], JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?></script><?php endif ?>
</head><body data-page="<?=e($page)?>">
<div class="announcement"><?=e(setting('announcement','Complimentary delivery across Karachi on orders above Rs. 2,000'))?> <a href="?page=shop">Shop now →</a></div>
<header class="site-header"><div class="container nav">
<a class="brand" href="<?=url()?>"><img src="<?=url($siteLogo)?>" alt="Darbar Sweets"></a>
<button class="nav-toggle" aria-label="Open navigation">☰</button>
<nav><a href="<?=url()?>">Home</a><a href="?page=shop">Shop</a><a href="?page=about">Our Story</a><a href="?page=contact">Contact</a></nav>
<div class="nav-actions"><button class="icon-btn search-btn" aria-label="Search products"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"></circle><path d="m20 20-4-4"></path></svg></button><a class="icon-btn" href="?page=account" aria-label="My account"><svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"></circle><path d="M4 21c1-5 4-7 8-7s7 2 8 7"></path></svg></a><button class="cart-open" aria-label="Open cart"><svg viewBox="0 0 24 24"><path d="M5 8h14l-1 13H6L5 8Z"></path><path d="M9 9V6a3 3 0 0 1 6 0v3"></path></svg><span class="cart-badge"><?=$cartCount?></span></button></div>
</div></header>
<main>
<?php if ($page === 'home'): ?>
<?php if($homeBanners):?><section class="banner-slider" aria-label="Darbar promotions"><div class="banner-track"><?php foreach($homeBanners as $i=>$banner):?><article class="banner-slide <?=$i===0?'active':''?>"><img src="<?=url($banner['image'])?>" alt="<?=e($banner['title']?:'Darbar Sweets promotion')?>"><?php if($banner['subtitle']||$banner['button_text']):?><div class="banner-caption"><?php if($banner['title']):?><h1><?=e($banner['title'])?></h1><?php endif?><p><?=e($banner['subtitle'])?></p><?php if($banner['button_text']):?><a class="btn btn-light" href="<?=e($banner['button_link']?:'?page=shop')?>"><?=e($banner['button_text'])?></a><?php endif?></div><?php endif?></article><?php endforeach?></div><div class="banner-dots"><?php foreach($homeBanners as $i=>$banner):?><span class="<?=$i===0?'active':''?>" aria-hidden="true"></span><?php endforeach?></div></section><?php else:?><section class="hero"><div class="hero-art"><img src="<?=url('uploads/products/darbar-originals/gulab-jamun.jpg')?>" alt="Darbar mithai"></div><div class="container hero-grid"><div class="hero-copy"><h1><?=e(setting('hero_heading','Tradition, wrapped in sweetness.'))?></h1><p><?=e(setting('hero_subtitle','Small-batch mithai made fresh daily.'))?></p><a class="btn" href="?page=shop">Explore the menu</a></div></div></section><?php endif?>
<section class="sweet-break" id="fresh"><div class="break-stage">
 <div class="break-copy"><span class="eyebrow">The moment of delight</span><h2>Handcrafted mithai,<br>made fresh daily.</h2><p>Every bite breaks open to reveal honest ingredients, patient craft and a little celebration.</p></div>
 <div class="sweet-composition photo-break"><img class="sweet-photo intact" src="<?=url('uploads/products/darbar-originals/gulab-jamun.jpg')?>" alt="Real photographed gulab jamun"><img class="sweet-photo sweet-half left" src="<?=url('uploads/products/darbar-originals/gulab-jamun.jpg')?>" alt=""><img class="sweet-photo sweet-half right" src="<?=url('uploads/products/darbar-originals/gulab-jamun.jpg')?>" alt=""><img class="syrup-photo" src="<?=url('uploads/products/darbar-originals/brown-cham-cham.jpg')?>" alt=""></div>
</div></section>
<section class="section categories"><div class="container"><div class="section-head reveal"><div><span class="eyebrow">Find your favourite</span><h2>A sweet for every moment</h2></div><a href="?page=shop">View the full menu →</a></div>
<div class="category-grid"><?php foreach ($homeCategories as $cat): ?><a class="category-card reveal" href="?page=shop&category=<?=urlencode($cat['name'])?>"><img src="<?=url($cat['image']?:'uploads/products/darbar-originals/gulab-jamun.jpg')?>" alt="<?=e($cat['name'])?>"><div><h3><?=e($cat['name'])?></h3><p><?=e($cat['description']?:'Freshly prepared Darbar favourites.')?></p></div></a><?php endforeach ?></div></div></section>
<section class="section products-section"><div class="container"><div class="section-head reveal"><div><span class="eyebrow">Darbar favourites</span><h2>Loved, gifted, remembered</h2></div><a href="?page=shop">Shop all sweets →</a></div><div class="product-grid"><?php foreach (array_slice($items,0,8) as $product) require __DIR__.'/views/product-card.php'; ?></div></div></section>
<section class="usp"><div class="container usp-grid"><?php foreach ([['◇','Pure ingredients','No shortcuts, ever.'],['✦','Made fresh daily','Small batches each morning.'],['⌁','Carefully packed','Arrives as beautiful as it left.'],['♧','Karachi delivery','Fast, reliable and chilled.']] as $u): ?><div class="reveal"><i><?=$u[0]?></i><div><h3><?=$u[1]?></h3><p><?=$u[2]?></p></div></div><?php endforeach ?></div></section>
<section class="section offer"><div class="container offer-inner reveal"><span>CELEBRATE TOGETHER</span><h2>Gifts that say more.</h2><p>Curated boxes for weddings, Eid and corporate milestones, finished by hand.</p><a class="btn btn-light" href="?page=contact">Plan a bespoke order</a></div></section>
<section class="section testimonials"><div class="container"><span class="eyebrow">From our customers</span><h2>Sweet words, shared freely</h2><div class="quote-grid"><blockquote>“The kaju katli disappeared before dinner even began. Beautifully packed and genuinely fresh.”<footer>— Ayesha K. · ★★★★★</footer></blockquote><blockquote>“Darbar handled 180 wedding boxes flawlessly. Every detail felt considered.”<footer>— Hammad R. · ★★★★★</footer></blockquote><blockquote>“That old-Karachi taste, delivered to the door. The gulab jamun is exceptional.”<footer>— Sana M. · ★★★★★</footer></blockquote></div></div></section>
<?php elseif ($page === 'shop'): ?>
<?php
$categoryScenes=[];
foreach($allCategories as $cat){
 $categoryScenes[$cat['name']]=[$cat['image']?:'uploads/products/darbar-originals/gulab-jamun.jpg',$cat['description']?:'Freshly prepared Darbar favourites.','split'];
}
$scene=$categoryScenes[$selectedCategory]??null;
if($selectedCategoryRow){$scene=[$selectedCategoryRow['image']?:'uploads/products/darbar-originals/gulab-jamun.jpg',$selectedCategoryRow['description']?:'Freshly prepared Darbar favourites.','split'];}
?>
<?php if($scene):?><section class="category-motion" data-motion="<?=e($scene[2])?>"><div class="category-stage"><div class="category-copy"><span class="eyebrow">Darbar collection</span><h1><?=e($selectedCategory)?></h1><p><?=e($scene[1])?></p></div><div class="category-object"><img class="cat-base" src="<?=url($scene[0])?>" alt="<?=e($selectedCategory)?>"><img class="cat-layer cat-layer-a" src="<?=url($scene[0])?>" alt=""><img class="cat-layer cat-layer-b" src="<?=url($scene[0])?>" alt=""></div></div></section>
<?php else:?><section class="page-hero"><div class="container"><span class="eyebrow">Freshly made</span><h1>Shop the Darbar</h1><p>Traditional favourites and modern gifts, prepared with the same uncompromising care.</p></div></section><?php endif?>
<section class="section"><div class="container shop-layout"><div class="shop-toolbar"><button type="button" class="btn btn-ghost filter-toggle" id="filterToggle" aria-expanded="false" aria-controls="filterPanel">Refine <span aria-hidden="true">▾</span></button><p class="shop-count"><span id="shopCount"><?=count($items)?></span> sweets</p></div><div class="filter-overlay" id="filterOverlay" hidden></div><aside class="filters" id="filterPanel" aria-hidden="true"><div class="filters-head"><h3>Refine</h3><button type="button" class="filter-close" id="filterClose" aria-label="Close filters">×</button></div><label>Search<input id="shopSearch" type="search" placeholder="Search sweets…" value="<?=e($query)?>"></label><label>Category<select id="categoryFilter"><option value="">All categories</option><?php foreach($allCategories as $cat):?><option <?=$selectedCategory===$cat['name']?'selected':''?>><?=e($cat['name'])?></option><?php endforeach?></select></label><label>Sort<select id="sortProducts"><option value="featured">Featured</option><option value="low">Price: Low to high</option><option value="high">Price: High to low</option></select></label><button type="button" class="btn btn-block" id="filterApply">Apply filters</button></aside><div class="product-grid shop-products"><?php foreach ($items as $product) require __DIR__.'/views/product-card.php'; ?></div></div></section>
<?php elseif ($page === 'product'): ?>
<?php $detail=$productDetail;?>
<?php if(!$detail):http_response_code(404);?><section class="page-hero"><div class="container"><h1>Sweet not found</h1><p>This product may no longer be available.</p><a class="btn btn-light" href="?page=shop">Browse the menu</a></div></section>
<?php else:$gallery=array_values(array_unique(array_filter(array_merge([$detail['image']],$detail['images']))));?>
<section class="section product-detail"><div class="container detail-grid"><div class="detail-gallery"><div class="detail-main tilt-card"><img id="detailMain" src="<?=url($gallery[0])?>" alt="<?=e($detail['name'])?>"></div><div class="thumbs"><?php foreach($gallery as $image):?><button data-gallery="<?=url($image)?>"><img src="<?=url($image)?>" alt=""></button><?php endforeach?></div></div><div class="detail-info"><span class="eyebrow"><?=e($detail['category'])?></span><h1><?=e($detail['name'])?></h1><p class="stars">★★★★★ <small>4.9 · freshly reviewed</small></p><p class="detail-price">Rs. <?=number_format((float)$detail['price'])?></p><p><?=e($detail['short_description'])?></p><?php if($detail['variants']):?><label>Choose size<select id="productVariant"><?php foreach($detail['variants'] as $variant):?><option value="<?=$variant['id']?>" data-price="<?=$variant['price']?>"><?=e($variant['label'])?> — Rs. <?=number_format($variant['price'])?></option><?php endforeach?></select></label><?php endif?><div class="buy-row"><label>Quantity<input id="detailQty" type="number" min="1" max="20" value="1"></label><button class="btn add-cart detail-add" data-id="<?=$detail['id']?>" data-name="<?=e($detail['name'])?>" data-price="<?=$detail['price']?>" data-image="<?=url($detail['image'])?>">Add to bag</button></div><div class="detail-tabs"><details open><summary>Description</summary><p><?=nl2br(e($detail['description']?:$detail['short_description']))?></p></details><details><summary>Ingredients & allergens</summary><p><?=e($detail['ingredients']?:'Milk solids, sugar, pure ghee, nuts and cardamom.')?><br><b>Allergens:</b> <?=e($detail['allergens']?:'Contains dairy and nuts.')?></p></details></div></div></div></section>
<?php endif?>
<?php elseif (in_array($page,['login','register'],true)): ?>
<section class="auth-page"><form class="auth-card" method="post"><?=csrf_field()?><img src="<?=url('uploads/logo/darbar-sweets-logo.png')?>" alt="Darbar Sweets"><span class="eyebrow"><?=$page==='login'?'Welcome back':'Join the Darbar'?></span><h1><?=$page==='login'?'Sign in':'Create account'?></h1><?php if($authError):?><p class="form-alert"><?=e($authError)?></p><?php endif?><?php if($page==='register'):?><label>Full name<input name="name" required autocomplete="name"></label><label>Phone<input name="phone" required autocomplete="tel"></label><?php endif?><label><?=$page==='login'?'Email or phone':'Email'?><input name="<?=$page==='login'?'login':'email'?>" <?=$page==='login'?'':'type="email"'?> required autocomplete="<?=$page==='login'?'username':'email'?>"></label><label>Password<input type="password" name="password" minlength="8" required autocomplete="<?=$page==='login'?'current-password':'new-password'?>"></label><button class="btn btn-block"><?=$page==='login'?'Sign in securely':'Create my account'?></button><p><?=$page==='login'?'New to Darbar? <a href="?page=register">Create an account</a>':'Already registered? <a href="?page=login">Sign in</a>'?></p></form></section>
<?php elseif ($page === 'account'): ?>
<?php $me=customer();$orders=[];if($pdo){$q=$pdo->prepare("SELECT order_number,total,status,created_at FROM orders WHERE user_id=? ORDER BY id DESC");$q->execute([$me['id']]);$orders=$q->fetchAll();}?>
<section class="page-hero compact"><div class="container"><span class="eyebrow">My Darbar</span><h1>Assalam-o-alaikum, <?=e(explode(' ',$me['name'])[0])?>.</h1></div></section><section class="section"><div class="container account-grid"><aside class="account-nav"><b>My account</b><a class="active" href="#profile">Profile</a><a href="#orders">Orders</a><a href="?page=logout">Sign out</a></aside><div><section class="panel-card" id="profile"><h2>Profile information</h2><div class="profile-grid"><p><small>Name</small><?=e($me['name'])?></p><p><small>Email</small><?=e($me['email'])?></p><p><small>Phone</small><?=e($me['phone'])?></p><p><small>Member since</small><?=date('F Y',strtotime($me['created_at']))?></p></div></section><section class="panel-card" id="orders"><h2>Order history</h2><div class="responsive-table"><table><thead><tr><th>Order</th><th>Date</th><th>Total</th><th>Status</th></tr></thead><tbody><?php if($orders):foreach($orders as $order):?><tr><td><b><?=e($order['order_number'])?></b></td><td><?=date('d M Y',strtotime($order['created_at']))?></td><td>Rs. <?=number_format($order['total'])?></td><td><span class="status <?=e($order['status'])?>"><?=e(str_replace('_',' ',$order['status']))?></span></td></tr><?php endforeach;else:?><tr><td colspan="4" class="empty-cell">No orders yet. <a href="?page=shop">Choose something sweet.</a></td></tr><?php endif?></tbody></table></div></section></div></div></section>
<?php elseif ($page === 'cart'): ?>
<section class="page-hero compact"><div class="container"><span class="eyebrow">Your selection</span><h1>Shopping bag</h1></div></section><section class="section"><div class="container cart-page" id="fullCart"></div></section>
<?php elseif ($page === 'checkout'): ?>
<section class="page-hero compact"><div class="container"><div class="steps">Bag <b>→ Details →</b> Payment → Confirmation</div><h1>Checkout</h1></div></section><section class="section"><form class="container checkout-grid" method="post" action="<?=url('api/order.php')?>"><?=csrf_field()?><div class="form-card"><h2>Delivery details</h2><div class="form-grid"><label>Full name<input required name="name"></label><label>Phone<input required name="phone" inputmode="tel"></label><label>Email<input required type="email" name="email"></label><label>City<select name="city"><option>Karachi</option><option>Lahore</option><option>Islamabad</option></select></label><label class="full">Delivery address<textarea required name="address"></textarea></label><label class="full">Order notes<textarea name="notes"></textarea></label></div><h2>Payment</h2><div class="payment-options"><label><input checked type="radio" name="payment" value="cod"> Cash on delivery</label><label><input type="radio" name="payment" value="card"> Visa / Mastercard</label><label><input type="radio" name="payment" value="jazzcash"> JazzCash</label><label><input type="radio" name="payment" value="easypaisa"> Easypaisa</label></div></div><aside class="order-summary"><h3>Your order</h3><div id="checkoutItems"></div><button class="btn btn-block">Place order securely</button><small>By ordering, you agree to our terms and return policy.</small></aside></form></section>
<?php elseif (in_array($page,['about','contact','faqs','terms','privacy','returns','track'],true)): ?>
<section class="page-hero"><div class="container"><span class="eyebrow">Darbar Sweets</span><h1><?=e($title)?></h1><p><?= $page==='about'?e(setting('about_para1','A family tradition of hospitality, craft and uncompromising flavour.')):e(setting('contact_hero_text','We are here to make every celebration a little sweeter.')) ?></p></div></section>
<?php if($page==='about'):?><section class="section story"><div class="container story-grid"><div class="story-image tilt-card"><img src="<?=url(setting('about_image','assets/images/kaju-katli.png'))?>" alt="Darbar Sweets traditional sweets"></div><div><span class="eyebrow"><?=e(setting('about_eyebrow','Our beginning'))?></span><h2><?=e(setting('about_heading','Made with patience since 1989.'))?></h2><p><?=e(setting('about_para1','Darbar began as one family counter in Karachi, where every tray was cooked in small batches and every customer was welcomed like a guest. More than three decades later, the scale has changed—but the standard has not.'))?></p><p><?=e(setting('about_para2','Our karigars balance recipes by aroma, colour and touch. Pure ghee, fresh milk, real nuts and whole spices come first. Shortcuts never do.'))?></p><div class="story-numbers"><b><?=e(setting('about_stat1_num','35+'))?><small><?=e(setting('about_stat1_label','years of craft'))?></small></b><b><?=e(setting('about_stat2_num','24h'))?><small><?=e(setting('about_stat2_label','fresh-batch promise'))?></small></b><b><?=e(setting('about_stat3_num','4.9★'))?><small><?=e(setting('about_stat3_label','customer rating'))?></small></b></div></div></div></section><section class="section values"><div class="container"><span class="eyebrow">What guides us</span><h2><?=e(setting('about_values_heading','Old soul. Modern standard.'))?></h2><div class="quote-grid"><blockquote><?=e(setting('about_value1_title','Pure ingredients'))?><footer><?=e(setting('about_value1_text','Real milk, ghee, nuts and spices—selected without compromise.'))?></footer></blockquote><blockquote><?=e(setting('about_value2_title','Karigar craft'))?><footer><?=e(setting('about_value2_text','Traditional technique, practiced patiently and passed forward.'))?></footer></blockquote><blockquote><?=e(setting('about_value3_title','Gift-worthy care'))?><footer><?=e(setting('about_value3_text','Every order is packed as though it is going to our own family.'))?></footer></blockquote></div></div></section>
<?php elseif($page==='contact'):?><section class="section"><div class="container contact-grid"><div><span class="eyebrow">Visit the Darbar</span><h2>Come say salaam.</h2><div class="contact-cards"><article><b><?=e(setting('contact_store_title','Flagship store'))?></b><p><?=nl2br(e(setting('contact_address',"Main Tariq Road, PECHS\nKarachi, Pakistan")))?></p></article><article><b>Talk to us</b><p><?=e(setting('contact_phone','+92 21 111 327 227'))?><br>WhatsApp: <?=e(setting('contact_whatsapp','+92 300 327 2277'))?></p></article><article><b>Opening hours</b><p><?=nl2br(e(setting('contact_hours',"Monday–Sunday\n9:00 AM–11:00 PM")))?></p></article></div><div class="map-card"><?=e(setting('contact_map_text','Darbar Sweets · Tariq Road, Karachi'))?></div></div><form class="form-card"><span class="eyebrow">Send an enquiry</span><h2>How can we help?</h2><label>Name<input required></label><label>Email<input type="email" required></label><label>Phone<input type="tel"></label><label>Enquiry type<select><option>General enquiry</option><option>Wedding order</option><option>Corporate gifting</option><option>Delivery support</option></select></label><label>Message<textarea required></textarea></label><button class="btn">Send message</button></form></div></section>
<?php else:?><section class="section"><div class="container prose"><?php if($page==='track'): ?><form class="form-card track-form"><h2>Where is my order?</h2><label>Order ID<input required placeholder="DS-2026-001"></label><label>Phone number<input required></label><button class="btn">Track order</button></form><?php else: ?><h2><?=e($title)?></h2><p>Darbar Sweets began with a simple promise: make traditional mithai properly, with patience and generosity. That promise continues in every tray, box and celebration we prepare.</p><h3>Our commitment</h3><p>We select ingredients carefully, cook in small batches and pack every order with the attention we would give a gift for our own family.</p><?php endif ?></div></section><?php endif?>
<?php else: ?><section class="page-hero"><div class="container"><h1><?=e($title)?></h1><p>This secure area is ready for database-backed account access.</p><a class="btn" href="?page=shop">Continue shopping</a></div></section><?php endif ?>
</main>
<div class="search-panel" aria-hidden="true"><button class="search-close" aria-label="Close search">×</button><form action="<?=url()?>" method="get"><input type="hidden" name="page" value="shop"><label for="globalSearch">What are you craving?</label><div><input id="globalSearch" name="q" type="search" placeholder="Try “gulab jamun” or “gift box”" autocomplete="off"><button class="btn">Search</button></div><small>Search across fresh mithai, halwa, bakery and gifts.</small></form></div>
<section class="newsletter"><div class="container"><div><span class="eyebrow">A little sweetness in your inbox</span><h2>First taste of new boxes & offers.</h2></div><form><input type="email" aria-label="Email" placeholder="Your email address" required><button class="btn">Join the Darbar</button></form></div></section>
<footer class="footer"><div class="container footer-grid"><div><img src="<?=url('uploads/logo/darbar-sweets-logo.png')?>" alt="Darbar Sweets"><p>Handcrafted mithai and thoughtful gifting from the heart of Karachi.</p></div><div><h3>Explore</h3><a href="?page=shop">Shop</a><a href="?page=about">Our story</a><a href="?page=track">Track order</a></div><div><h3>Help</h3><a href="?page=faqs">FAQs</a><a href="?page=returns">Returns</a><a href="?page=privacy">Privacy</a></div><div><h3>Visit</h3><p>Main Tariq Road, Karachi<br>Daily, 9am–11pm<br>+92 21 111 327 227</p></div></div><div class="container footer-bottom">© <?=date('Y')?> Darbar Sweets <div class="payment-logos" aria-label="Accepted payment methods"><img src="<?=url('assets/images/payments/visa.svg')?>" alt="Visa"><img src="<?=url('assets/images/payments/mastercard.svg')?>" alt="Mastercard"><img src="<?=url('assets/images/payments/jazzcash.svg')?>" alt="JazzCash"><img src="<?=url('assets/images/payments/easypaisa.svg')?>" alt="Easypaisa"></div></div></footer>
<div class="cart-overlay"></div><aside class="cart-drawer" aria-hidden="true"><header><div><small>Your Darbar bag</small><h2>Cart <span class="cart-badge"><?=$cartCount?></span></h2></div><button class="cart-close" aria-label="Close">×</button></header><div class="cart-lines"></div><footer><div><span>Subtotal</span><strong class="cart-subtotal">Rs. 0</strong></div><a class="btn btn-block" href="?page=checkout">Checkout</a><a class="text-link" href="?page=cart">View full bag</a></footer></aside>
<div class="toast" role="status"></div>
<script>window.DARBAR={base:"<?=url()?>",csrf:"<?=csrf_token()?>",cart:<?=json_encode($_SESSION['cart']??[])?>}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/ScrollTrigger.min.js"></script>
<script src="<?=url('assets/js/app.js')?>"></script></body></html>
